pipeline:
  publish_ecr:
    image: plugins/docker
    repo: drone-ecr-auth
    tags: [ "latest" ]
    ecr_region: ap-southeast-1
    dockerfile: Dockerfile
    debug: true
    event: push
    secrets: [ ecr_access_key, ecr_secret_key ]