pipeline:
  publish_ecr:
    image: plugins/ecr
    repo: 234232853477.dkr.ecr.ap-southeast-1.amazonaws.com/drone-ecr-auth
    registry: 234232853477.dkr.ecr.ap-southeast-1.amazonaws.com
    tags: [ "latest" ]
    ecr_region: ap-southeast-1
    dockerfile: Dockerfile
    debug: true
    event: push
    secrets: [ ecr_access_key, ecr_secret_key ]