pipeline:
  publish_ecr:
    image: plugins/ecr
    repo: drone-ecr-auth
    tags: [ "latest" ]
    dockerfile: Dockerfile
    secrets: [ ecr_region ]
    when:
      branch: master
      event: push
